export const ORDER_SAVE_REQUEST = 'ORDER_SAVE_REQUEST'
export const ORDER_SAVE_SUCCESS = 'ORDER_SAVE_SUCCESS'
export const ORDER_SAVE_FAIL = 'ORDER_SAVE_FAIL'

export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST'
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS'
export const ORDER_DETAIL_FAIL = 'ORDER_DETAIL_FAIL'
export const ORDER_DETAIL_RESET = 'ORDER_DETAIL_RESET'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

export const LIST_MY_ORDERS_REQUEST = 'LIST_MY_ORDERS_REQUEST'
export const LIST_MY_ORDERS_SUCCESS = 'LIST_MY_ORDERS_SUCCESS'
export const LIST_MY_ORDERS_FAIL = 'LIST_MY_ORDERS_FAIL'
export const LIST_MY_ORDERS_RESET = 'LIST_MY_ORDERS_RESET'