export const ORDER_SAVE_REQUEST = 'ORDER_SAVE_REQUEST'
export const ORDER_SAVE_SUCCESS = 'ORDER_SAVE_SUCCESS'
export const ORDER_SAVE_FAIL = 'ORDER_SAVE_FAIL'

export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST'
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS'
export const ORDER_DETAIL_FAIL = 'ORDER_DETAIL_FAIL'
export const ORDER_DETAIL_RESET = 'ORDER_DETAIL_RESET'