export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL"

export const DETAILS_PRODUCT_REQUEST = "DETAILS_PRODUCT_REQUEST"
export const DETAILS_PRODUCT_SUCCESS = "DETAILS_PRODUCT_SUCCESS"
export const DETAILS_PRODUCT_FAIL = "DETAILS_PRODUCT_FAIL"

// constant untuk delete product by admin
export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL"


// constant untuk create product
export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL'
export const CREATE_PRODUCT_RESET = 'CREATE_PRODUCT_RESET'