export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL"

export const DETAILS_PRODUCT_REQUEST = "DETAILS_PRODUCT_REQUEST"
export const DETAILS_PRODUCT_SUCCESS = "DETAILS_PRODUCT_SUCCESS"
export const DETAILS_PRODUCT_FAIL = "DETAILS_PRODUCT_FAIL"