export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST"
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL"

export const DETAILS_PRODUCT_REQUEST = "DETAILS_PRODUCT_REQUEST"
export const DETAILS_PRODUCT_SUCCESS = "DETAILS_PRODUCT_SUCCESS"
export const DETAILS_PRODUCT_FAIL = "DETAILS_PRODUCT_FAIL"

// constant untuk delete product by admin
export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL"


// constant untuk create product
export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL'
export const CREATE_PRODUCT_RESET = 'CREATE_PRODUCT_RESET'

export const EDIT_PRODUCT_REQUEST = 'EDIT _PRODUCT_REQUEST'
export const EDIT_PRODUCT_SUCCESS = 'EDIT _PRODUCT_SUCCESS'
export const EDIT_PRODUCT_FAIL = 'EDIT _PRODUCT_FAIL'
export const EDIT_PRODUCT_RESET = 'EDIT _PRODUCT_RESET'

export const REVIEW_PRODUCT_REQUEST = 'REVIEW _PRODUCT_REQUEST'
export const REVIEW_PRODUCT_SUCCESS = 'REVIEW _PRODUCT_SUCCESS'
export const REVIEW_PRODUCT_FAIL = 'REVIEW _PRODUCT_FAIL'
export const REVIEW_PRODUCT_RESET = 'REVIEW _PRODUCT_RESET'

export const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST'
export const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS'
export const PRODUCT_TOP_FAIL = 'PRODUCT_TOP_FAIL'
export const PRODUCT_TOP_RESET = 'PRODUCT_TOP_RESET'